(function(){'use strict';
const cfg=window.FIREBASE_CONFIG||{};const configured=cfg.apiKey&&!String(cfg.apiKey).includes('INSERISCI_');const loginScreen=document.getElementById('loginScreen'),loginBtn=document.getElementById('googleLoginBtn'),loginError=document.getElementById('loginError');
if(!configured){loginError.textContent='Configurazione Firebase da completare in firebase-config.js';loginBtn.disabled=true;return}
const app=firebase.initializeApp(cfg),auth=app.auth(),db=app.firestore();auth.languageCode='it';
try{db.enablePersistence({synchronizeTabs:true}).catch(e=>console.warn('Persistenza offline Firestore non disponibile',e))}catch(e){console.warn(e)}
auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(e=>console.warn('Persistenza accesso Google non disponibile',e));
let currentUser=null,userWaiters=[],listeners=[];function resolveUserWaiters(user){const p=userWaiters.slice();userWaiters=[];p.forEach(r=>r(user))}function waitForUser(){return currentUser?Promise.resolve(currentUser):new Promise(r=>userWaiters.push(r))}function cloudRef(user,key){return db.collection('users').doc(user.uid).collection('registroLavoro').doc(key)}function localKey(key){return'registroLavoro:'+key}
function startListeners(user){listeners.forEach(u=>{try{u()}catch(e){}});listeners=[];['pratiche-data','candidature-data'].forEach(key=>{const unsub=cloudRef(user,key).onSnapshot(snapshot=>{if(!snapshot.exists)return;const data=snapshot.data()||{};if(typeof data.value!=='string')return;try{localStorage.setItem(localKey(key),data.value)}catch(e){}window.dispatchEvent(new CustomEvent('cloud-storage-change',{detail:{key,value:data.value}}))},e=>console.warn('Listener Firestore non disponibile',key,e));listeners.push(unsub)})}
window.storage={async get(key){const user=await waitForUser();try{const snap=await cloudRef(user,key).get();if(snap.exists&&typeof snap.data().value==='string'){const value=snap.data().value;try{localStorage.setItem(localKey(key),value)}catch(e){}return{value}}}catch(e){console.warn('Lettura Firestore non riuscita',e)}try{return{value:localStorage.getItem(localKey(key))}}catch(e){return{value:null}}},async set(key,value){const user=await waitForUser();try{localStorage.setItem(localKey(key),value)}catch(e){}try{await cloudRef(user,key).set({value,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return true}catch(e){console.warn('Scrittura Firestore non riuscita',e);return !navigator.onLine}}};
function setStatus(text,mode){const el=document.getElementById('cloudStatus'),dot=document.getElementById('cloudDot');if(el)el.textContent=text;if(dot)dot.className='cloud-dot'+(mode?' '+mode:'')}
async function signIn(){loginError.textContent='';loginBtn.disabled=true;const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{await auth.signInWithPopup(provider)}catch(e){if(e.code==='auth/unauthorized-domain')loginError.textContent='Il dominio GitHub Pages non è autorizzato in Firebase.';else if(e.code==='auth/popup-blocked')loginError.textContent='Il browser ha bloccato il popup Google.';else if(e.code!=='auth/popup-closed-by-user')loginError.textContent='Accesso Google non riuscito: '+(e.code||e.message||'errore');loginBtn.disabled=false}}
loginBtn.addEventListener('click',signIn);auth.onAuthStateChanged(user=>{if(user){currentUser=user;document.body.classList.remove('auth-pending');loginScreen.hidden=true;const email=document.getElementById('cloudEmail');if(email)email.textContent=user.email||'';setStatus(navigator.onLine?'Sincronizzato':'Offline · dati locali',navigator.onLine?'':'offline');resolveUserWaiters(user);startListeners(user)}else{currentUser=null;document.body.classList.add('auth-pending');loginScreen.hidden=false;loginBtn.disabled=false}});window.addEventListener('online',()=>currentUser&&setStatus('Connessione ripristinata','pending'));window.addEventListener('offline',()=>currentUser&&setStatus('Offline · modifiche locali','offline'));window.REGISTRO_AUTH={signOut:()=>auth.signOut(),getUser:()=>currentUser};
})();
